// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:ddai_community/main.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: firebaseWebApiKey,
    appId: '1:709883883276:web:086378133700328f8fe329',
    messagingSenderId: '709883883276',
    projectId: 'ddai-community',
    authDomain: 'ddai-community.firebaseapp.com',
    storageBucket: 'ddai-community.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: firebaseAndroidApiKey,
    appId: '1:709883883276:android:231988df36c998c08fe329',
    messagingSenderId: '709883883276',
    projectId: 'ddai-community',
    databaseURL:
        'https://ddai-community-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ddai-community.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: firebaseIosApiKey,
    appId: '1:709883883276:ios:a9eeebf2fd5ea8588fe329',
    messagingSenderId: '709883883276',
    projectId: 'ddai-community',
    databaseURL:
        'https://ddai-community-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ddai-community.firebasestorage.app',
    iosBundleId: 'com.ddai.ddaiCommunity',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: firebaseIosApiKey,
    appId: '1:709883883276:ios:4171059dbaa78cba8fe329',
    messagingSenderId: '709883883276',
    projectId: 'ddai-community',
    storageBucket: 'ddai-community.firebasestorage.app',
    iosBundleId: 'com.ddai.ddaiCommunity',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: firebaseWebApiKey,
    appId: '1:709883883276:web:bb69da44ec96241c8fe329',
    messagingSenderId: '709883883276',
    projectId: 'ddai-community',
    authDomain: 'ddai-community.firebaseapp.com',
    storageBucket: 'ddai-community.firebasestorage.app',
  );
}
